[armnn] compilation error - missing initializer
correction for compilation error:

tensor_filter_armnn.cc: In function 'int armnn_open(const GstTensorFilterProperties*, void**)':
nnstreamer_plugin_api_filter.h:568:76: error: missing initializer for member 'parse_accl_args::auto_accl' [-Werror=missing-field-initializers]
    #define parse_accl_hw(...) parse_accl_hw_fill((parse_accl_args){__VA_ARGS__})
                                                                               ^
tensor_filter_armnn.cc:672:8: note: in expansion of macro 'parse_accl_hw'
    hw = parse_accl_hw (prop->accl_str, armnn_accl_support);
         ^~~~~~~~~~~~~

Signed-off-by: Julien Vuillaumier <julien.vuillaumier@nxp.com>