[Build] Fix build for clang compielr on armv7l
Related open source issue:
https://www.github.com/nnstreamer/nnstreamer/issues/4822

Error1:
[  100s] armv7l-tizen-linux-gnueabi-clang: error: unknown argument: '-mfp16-format=ieee'

Solution1:
The `-mfp16-format=ieee` option is GCC-specific; Clang does not support this option.
The LLVM documentation states that it is equivalent to IEEE's __fp16 behavior by default, so this option is unnecessary:
https://clang.llvm.org/docs/LanguageExtensions.html

Error2:
Undefined reference to '__aeabi_d2h'

Solution2:
This function is provided by compiler-rt. You need to add the compiler-rt dependency in BuildRequires and add the linking option -rtlib=compiler-rt when compiling nnstreamer.

Error3:
Undefined reference to '__aeabi_unwind_cpp_pr0'

Solution3.1 (this patchset solution):
Since the LLVM project in the environment does not compile libunwind, there is no unwind library to use. So add -unwindlib=libgcc to use GCC's libgcc instead.

Solution3.2:
Recompile the LLVM project and enable libunwind in -DLLVM_ENABLE_PROJECTS.

Change-Id: I96124e40cda735db1bfcb5f88ad0edd8684a184d
Signed-off-by: Kai Cheng <kai.cheng@samsung.com>
Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>