[armnn] compilation error - unused parameter
correction for multiple occurences of compilation error:

error: unused parameter '[parameter name]' [-Werror=unused-parameter]

Signed-off-by: Julien Vuillaumier <julien.vuillaumier@nxp.com>